Repository Mbed-TLS/mbedtls-framework, pull requests merged in 2024-09, with the labels that each got.

#45 Projects and Mbed TLS 3.6 detection
  scripts/mbedtls_framework/build_tree.py
Labels: approved

#44 ssl-opt: improve PSK mode detection
  data_files/simplepass.psk
Labels: approved, priority-high, size-xs

#43 Update data_files/.gitignore with test output
  data_files/.gitignore
Labels: enhancement, needs-review, needs-reviewer, priority-medium, size-xs

#41 Move `config.py` functionalities to the framework
  scripts/generate_config_tests.py
  scripts/mbedtls_framework/config_common.py
Labels: enhancement, needs-review, size-s, priority-high

#34 Replace MBEDTLS_PK_HAVE_ECC_KEYS with PSA_WANT_KEY_TYPE_ECC_PUBLIC_KEY
  scripts/generate_config_tests.py
  scripts/generate_pkcs7_tests.py
Labels: enhancement, approved, priority-high, size-xs
