Repository Mbed-TLS/mbedtls-framework, pull requests merged in 2024-07, with the labels that each got.

#30 Update crypto header directories
  scripts/mbedtls_framework/psa_storage.py
Labels: enhancement, needs-review, priority-high, priority-very-high

#32 Adapt to crypto modules migration
  scripts/mbedtls_framework/build_tree.py
Labels: enhancement, approved, priority-high

#25 Feature: code wrappers subpackage
  scripts/generate_psa_wrappers.py
  scripts/mbedtls_framework/c_parsing_helper.py
  scripts/mbedtls_framework/c_wrapper_generator.py
  scripts/mbedtls_framework/code_wrapper/__init__.py
  scripts/mbedtls_framework/code_wrapper/psa_buffer.py
  scripts/mbedtls_framework/code_wrapper/psa_test_wrapper.py
  scripts/mbedtls_framework/code_wrapper/psa_wrapper.py
Labels: needs-review, size-s, priority-high

#36 Adapt to the move of crypto test suites to tf-psa-crypto directory
  scripts/mbedtls_framework/psa_information.py
  scripts/mbedtls_framework/psa_storage.py
Labels: enhancement, needs-ci, priority-high

#38 c_wrapper_generator: Increased robustness of whitespace capture.
  scripts/mbedtls_framework/c_wrapper_generator.py
Labels: needs-review, needs-reviewer, priority-medium, size-xs
