Repository Mbed-TLS/mbedtls-framework, pull requests merged in 2024-08, with the labels that each got.

#35 Use updated config.py classes
  scripts/generate_config_tests.py
Labels: enhancement, needs-review, priority-high, size-xs

#23 Generate static test functions & wrappers
  scripts/generate_test_code.py
  scripts/test_generate_test_code.py
Labels: approved, priority-high, size-xs

#42 Fix everest build issue
  scripts/mbedtls_framework/psa_storage.py
Labels: approved, priority-low, priority-medium, size-xs
