Repository Mbed-TLS/mbedtls-framework, pull requests merged in 2024-06, with the labels that each got.

#21 Add test generation files to framework
  scripts/generate_bignum_tests.py
  scripts/generate_ecp_tests.py
  scripts/generate_pkcs7_tests.py
  scripts/generate_psa_tests.py
  scripts/generate_psa_wrappers.py
  scripts/generate_test_cert_macros.py
  scripts/generate_test_code.py
  scripts/generate_test_keys.py
  scripts/test_generate_test_code.py
Labels: needs-review, priority-high

#26 Adjust temporarily the location of PSA headers
  scripts/generate_psa_wrappers.py
  scripts/mbedtls_framework/psa_information.py
  scripts/mbedtls_framework/psa_storage.py
Labels: enhancement, approved

#22 Fix generation of PSA test wrappers for PAKE
  scripts/generate_psa_wrappers.py
Labels: approved
