Repository Mbed-TLS/mbedtls-framework, pull requests merged in 2024-12, with the labels that each got.

#81 Update for TF-PSA-Crypto `config.py`
  scripts/generate_config_tests.py
  scripts/mbedtls_framework/config_common.py
Labels: enhancement, needs-review, priority-high

#80 Move scripts used by all-core.sh to the framework
  scripts/all-core.sh
  scripts/output_env.sh
  scripts/quiet/cmake
  scripts/quiet/make
  scripts/quiet/quiet.sh
Labels: enhancement, approved, size-s, priority-high

#99 Finalize split preparation-2
  scripts/generate_psa_wrappers.py
  scripts/generate_test_keys.py
Labels: enhancement, needs-review, priority-high

#59 Add pull request template
  .github/pull_request_template.md
Labels: approved, priority-medium, size-xs

#100 Move scripts/code_style.py to the framework
  scripts/code_style.py
Labels: enhancement, needs-review, size-s, priority-high

#84 Move check_files.py to the framework
  scripts/check_files.py
Labels: enhancement, needs-review, size-s, priority-high

#83 Switch generate_psa_test.py to automatic dependencies for positive test cases
  scripts/generate_psa_tests.py
  scripts/mbedtls_framework/crypto_data_tests.py
  scripts/mbedtls_framework/psa_information.py
  scripts/mbedtls_framework/psa_test_case.py
  scripts/mbedtls_framework/test_case.py
Labels: needs-review, needs-reviewer, size-s, priority-high

#96 Undo temporary changes in all-helpers.sh
  scripts/all-helpers.sh
Labels: enhancement, needs-review, needs-reviewer, priority-high, size-xs

#108 Ignore TF-PSA-Crypto and mbedtls build product
  tests/.gitignore
Labels: approved, needs-review, priority-medium, size-xs
