Repository Mbed-TLS/mbedtls-framework, pull requests merged in 2024-11, with the labels that each got.

#61 Add a Python utility function to get the 3.6 feature macro
  scripts/generate_config_tests.py
  scripts/generate_pkcs7_tests.py
  scripts/mbedtls_framework/test_case.py
Labels: enhancement, approved, priority-high, size-xs

#68 Move all-core and all-helpers to the framework
  scripts/all-core.sh
  scripts/all-helpers.sh
Labels: approved, priority-high, size-xs

#78 Port `psa_exercise_key` changes added mid-framework-move
  tests/include/test/psa_exercise_key.h
  tests/src/psa_exercise_key.c
Labels: approved, priority-very-high

#79 Remove MBEDTLS_PSA_CRYPTO_CONFIG-2
  scripts/all-core.sh
  scripts/all-helpers.sh
  tests/include/test/drivers/config_test_driver.h
  tests/include/test/drivers/crypto_config_test_driver_extension.h
Labels: enhancement, needs-review, priority-high

#67 Add project and branch detection in shell
  scripts/all-core.sh
  scripts/mbedtls_framework/build_tree.py
  scripts/project_detection.sh
Labels: enhancement, approved, size-s, priority-high
