Repository Mbed-TLS/mbedtls-framework, pull requests merged in 2024-10, with the labels that each got.

#55 Framework: Split check_test_cases.py and outcome_analysis.py
  scripts/check_test_cases.py
  scripts/mbedtls_framework/collect_test_cases.py
  scripts/mbedtls_framework/outcome_analysis.py
Labels: approved, size-s, priority-high

#48 enhance common_config.py and generate_test_code.py
  scripts/generate_test_code.py
  scripts/mbedtls_framework/config_common.py
Labels: needs-review, priority-high, size-xs

#33 Add Jenkinsfile
  tests/.jenkins/Jenkinsfile
Labels: single-reviewer, priority-high, size-xs

#56 Move TLS auxiliary test scripts to the framework
  scripts/generate_ssl_debug_helpers.py
  scripts/generate_tls13_compat_tests.py
  scripts/translate_ciphers.py
Labels: enhancement, approved, size-s, priority-high

#58 PSA_WANT_xxx is only meaningful when PSA crypto is enabled
  scripts/generate_config_tests.py
Labels: approved, priority-high, size-xs

#47 Support crypto config usage in `depends.py`
  scripts/mbedtls_framework/c_build_helper.py
  scripts/mbedtls_framework/config_common.py
Labels: enhancement, needs-review, size-s, priority-high
