Repository Mbed-TLS/mbedtls-framework, pull requests merged in 2025-01, with the labels that each got.

#88 Add a SBOM template in CycloneDX format
  scripts/sbom.cdx.json
Labels: approved, priority-medium, size-xs

#77 Add out of source build functions for TF-PSA-Crypto
  scripts/all-core.sh
Labels: enhancement, approved

#95 Move "easy" basic checks scripts to the framework
  scripts/apidoc_full.sh
  scripts/assemble_changelog.py
  scripts/check-doxy-blocks.pl
  scripts/check-python-files.sh
  scripts/doxygen.sh
  scripts/recursion.pl
Labels: enhancement, approved, size-s, priority-high

#103 Move tests/scripts/check_names.py to the framework
  scripts/check_names.py
Labels: needs-review, needs-reviewer, priority-high, size-xs

#105 Move most of min_requirements.py to the framework
  scripts/mbedtls_framework/min_requirements.py
Labels: needs-review, size-s, priority-high

#116 Move pkgconfig.sh to the framework
  scripts/pkgconfig.sh
Labels: needs-review, needs-reviewer, priority-high, size-xs

#109 Enable check_files.py for TF-PSA-Crypto
  scripts/check_files.py
Labels: enhancement, needs-review, needs-reviewer, size-xs

#104 Switch generate_psa_test.py to automatic dependencies for negative test cases
  scripts/generate_psa_tests.py
  scripts/mbedtls_framework/psa_information.py
  scripts/mbedtls_framework/psa_test_case.py
Labels: approved, needs-ci, size-s, priority-high

#117 Adapt check_names.py for independent TF-PSA-Crypto testing
  scripts/check_names.py
Labels: enhancement, needs-review, size-s
