Repository Mbed-TLS/mbedtls-framework, pull requests merged in 2025-03, with the labels that each got.

#142 Generate TLS handshake defragmentation tests
  scripts/generate_tls_handshake_tests.py
  scripts/mbedtls_framework/tls_test_case.py
Labels: approved, needs-ci, size-s, priority-high

#143 Incremental TLS handshake defragmentation tests
  scripts/generate_tls_handshake_tests.py
Labels: approved, needs-preceding-pr, size-s, priority-high

#148 Merge of defragmentation feature branch onto main
  scripts/generate_tls_handshake_tests.py
  scripts/mbedtls_framework/tls_test_case.py
Labels: approved, priority-very-high, size-xs

#146 Remove the RSA-decryption key exchange
  scripts/translate_ciphers.py
Labels: enhancement, needs-review, priority-high

#149 Enable checking of generated files and code style in TF-PSA-Crypto
  scripts/code_style.py
  scripts/generate_config_tests.py
  scripts/generate_test_cert_macros.py
  scripts/generate_test_keys.py
  scripts/make_generated_files.py
  scripts/mbedtls_framework/build_tree.py
  scripts/mbedtls_framework/code_wrapper/psa_wrapper.py
Labels: enhancement, approved, priority-high
