Repository Mbed-TLS/mbedtls-framework, pull requests merged in 2025-04, with the labels that each got.

#152 Make generated files follow-up
  scripts/make_generated_files.py
Labels: enhancement, needs-review, priority-high

#151 [framework] MBEDTLS_PLATFORM_GET_ENTROPY_ALT in 4.0
  tests/src/fake_external_rng_for_test.c
Labels: needs-review, size-s, priority-high

#141 [framework] Add test_tf_psa_crypto_cmake_shared to components-build-system.sh
  scripts/demo_common.sh
  scripts/project_detection.sh
  tests/programs/dlopen_demo.sh
Labels: needs-review, size-s, priority-high

#156 Adjust scripts to accommodate public header move
  scripts/check-doxy-blocks.pl
  scripts/check_names.py
Labels: approved

#159 [framework] Make demo_common.sh usable on its own
  scripts/demo_common.sh
  tests/programs/dlopen_demo.sh
Labels: needs-review, priority-high, size-xs

#136 Fix union initialization in PSA operations for GCC 15: new test helpers
  tests/include/test/drivers/aead.h
  tests/include/test/drivers/asymmetric_encryption.h
  tests/include/test/drivers/cipher.h
  tests/include/test/drivers/hash.h
  tests/include/test/drivers/key_agreement.h
  tests/include/test/drivers/key_management.h
  tests/include/test/drivers/mac.h
  tests/include/test/drivers/pake.h
  tests/include/test/drivers/signature.h
  tests/include/test/drivers/test_driver_common.h
  tests/include/test/helpers.h
  tests/include/test/psa_crypto_helpers.h
  tests/src/helpers.c
  tests/src/psa_crypto_helpers.c
Labels: approved, needs-ci, priority-high, size-xs

#161 [framework] MBEDTLS_PLATFORM_GET_ENTROPY_ALT in 4.0
  scripts/generate_config_tests.py
  tests/include/test/fake_external_rng_for_test.h
  tests/src/fake_external_rng_for_test.c
Labels: approved, priority-high, size-xs

#163 Prepare for Pylint: Complain about a missing comma in multiline lists of strings
  scripts/mbedtls_framework/bignum_core.py
  scripts/mbedtls_framework/bignum_mod_raw.py
  scripts/mbedtls_framework/ecp.py
Labels: approved, priority-medium, size-xs

#165 [framework] MBEDTLS_PLATFORM_GET_ENTROPY_ALT in 4.0
  tests/include/test/fake_external_rng_for_test.h
  tests/src/fake_external_rng_for_test.c
Labels: approved, priority-high, size-xs
