Repository Mbed-TLS/mbedtls-framework, pull requests merged in 2025-08, with the labels that each got.

#197 [framework] Remove 224-bit curves (1/3)
  scripts/mbedtls_framework/ecp.py
Labels: approved, needs-ci, priority-high, size-xs

#200 [framework] scripts: test_psa_compliance: add exceptions for tests using secp224r1 (4/6)
  scripts/test_psa_compliance.py
Labels: approved, priority-high, size-xs

#175 Move private headers to a private directory
  tests/include/test/bignum_helpers.h
  tests/include/test/drivers/cipher.h
  tests/include/test/helpers.h
  tests/include/test/psa_crypto_helpers.h
  tests/src/bignum_helpers.c
  tests/src/drivers/test_driver_asymmetric_encryption.c
  tests/src/drivers/test_driver_cipher.c
  tests/src/drivers/test_driver_key_management.c
  tests/src/drivers/test_driver_signature.c
  tests/src/fake_external_rng_for_test.c
  tests/src/psa_crypto_helpers.c
  tests/src/psa_exercise_key.c
  tests/src/random.c
Labels: approved, size-s, priority-high

#202 Add private headers to check_names.py for the mbedtls main repository
  scripts/check_names.py
Labels: approved
